// [데이터 추가 구역] 노선별 주요 찍턴 역 리스트
const subwayData = {
    "1호선": [
        { name: "연천", mood: "#최전방 #조용한", exit: "1번 출구" },
        { name: "전곡", mood: "#구석기 #유적지", exit: "1번 출구" },
        { name: "청산", mood: "#시골풍경", exit: "1번 출구" },
        { name: "소요산", mood: "#등산 #단풍", exit: "1번 출구" },
        { name: "동두천", mood: "#미군부대 #이색적", exit: "1번 출구" },
        { name: "보산", mood: "#그래피티 #외국느낌", exit: "1번 출구" },
        { name: "동두천중앙", mood: "#재래시장", exit: "1번 출구" },
        { name: "지행", mood: "#동두천신시가지", exit: "1번 출구" },
        { name: "덕정", mood: "#서정대학", exit: "1번 출구" },
        { name: "덕계", mood: "#아파트단지", exit: "1번 출구" },
        { name: "양주", mood: "#조명박물관", exit: "1번 출구" },
        { name: "녹양", mood: "#의정부종합운동장", exit: "1번 출구" },
        { name: "가능", mood: "#을지대학교", exit: "1번 출구" },
        { name: "의정부", mood: "#행복로 #제일시장", exit: "6번 출구" },
        { name: "회룡", mood: "#경전철환승", exit: "1번 출구" },
        { name: "망월사", mood: "#신한대학교", exit: "3번 출구" },
        { name: "도봉산", mood: "#등산코스 #수락산", exit: "1번 출구" },
        { name: "도봉", mood: "#북부지방법원", exit: "2번 출구" },
        { name: "방학", mood: "#도봉구청", exit: "1번 출구" },
        { name: "창동", mood: "#포장마차거리", exit: "1번 출구" },
        { name: "녹천", mood: "#조용한주택가", exit: "2번 출구" },
        { name: "월계", mood: "#인덕대학교", exit: "3번 출구" },
        { name: "광운대", mood: "#대학가 #철길", exit: "1번 출구" },
        { name: "석계", mood: "#매운족발 #먹자골목", exit: "1번 출구" },
        { name: "신이문", mood: "#의릉", exit: "1번 출구" },
        { name: "외대앞", mood: "#글로벌음식 #대학가", exit: "1번 출구" },
        { name: "회기", mood: "#파전골목 #경희대", exit: "1번 출구" },
        { name: "청량리", mood: "#전통시장 #기차여행", exit: "1번 출구" },
        { name: "제기동", mood: "#약령시장 #한약방", exit: "2번 출구" },
        { name: "신설동", mood: "#풍물시장 #가죽시장", exit: "9번 출구" },
        { name: "동묘앞", mood: "#구제시장 #무한도전", exit: "3번 출구" },
        { name: "동대문", mood: "#DDP #패션", exit: "1번 출구" },
        { name: "종로5가", mood: "#광장시장 #육회", exit: "8번 출구" },
        { name: "종로3가", mood: "#익선동 #포차거리", exit: "6번 출구" },
        { name: "종각", mood: "#젊음의거리 #보신각", exit: "4번 출구" },
        { name: "시청", mood: "#덕수궁 #돌담길", exit: "1번 출구" },
        { name: "서울역", mood: "#기차여행 #남산", exit: "1번 출구" },
        { name: "남영", mood: "#열정도 #숙대입구", exit: "1번 출구" },
        { name: "용산", mood: "#아이파크몰 #전자상가", exit: "1번 출구" },
        { name: "노량진", mood: "#수산시장 #컵밥거리", exit: "1번 출구" },
        { name: "대방", mood: "#공군호텔", exit: "2번 출구" },
        { name: "신길", mood: "#메밀국수맛집", exit: "1번 출구" },
        { name: "영등포", mood: "#타임스퀘어", exit: "5번 출구" },
        { name: "신도림", mood: "#디큐브시티", exit: "1번 출구" },
        { name: "구로", mood: "#공구상가", exit: "1번 출구" }
    ],
    "2호선": [
        { name: "시청", mood: "#덕수궁 #시청광장", exit: "1번 출구" },
        { name: "을지로입구", mood: "#명동 #백화점", exit: "7번 출구" },
        { name: "을지로3가", mood: "#힙지로 #노포", exit: "10번 출구" },
        { name: "을지로4가", mood: "#조명거리 #방산시장", exit: "1번 출구" },
        { name: "동대문역사문화공원", mood: "#DDP #디자인", exit: "1번 출구" },
        { name: "신당", mood: "#떡볶이타운 #중앙시장", exit: "8번 출구" },
        { name: "상왕십리", mood: "#곱창거리", exit: "2번 출구" },
        { name: "왕십리", mood: "#엔터식스 #한양대", exit: "6번 출구" },
        { name: "한양대", mood: "#노천강당", exit: "2번 출구" },
        { name: "뚝섬", mood: "#블루보틀 #성수카페", exit: "1번 출구" },
        { name: "성수", mood: "#팝업스토어 #수제화", exit: "4번 출구" },
        { name: "건대입구", mood: "#양꼬치거리 #커먼그라운드", exit: "6번 출구" },
        { name: "구의", mood: "#먹자골목", exit: "1번 출구" },
        { name: "강변", mood: "#동서울터미널 #한강뷰", exit: "4번 출구" },
        { name: "잠실나루", mood: "#서울책보고", exit: "1번 출구" },
        { name: "잠실", mood: "#롯데월드 #석촌호수", exit: "3번 출구" },
        { name: "잠실새내", mood: "#신천먹자골목", exit: "4번 출구" },
        { name: "종합운동장", mood: "#야구장 #콘서트", exit: "6번 출구" },
        { name: "삼성", mood: "#코엑스 #별마당도서관", exit: "5번 출구" },
        { name: "선릉", mood: "#정릉 #오피스타운", exit: "8번 출구" },
        { name: "역삼", mood: "#센터필드", exit: "7번 출구" },
        { name: "강남", mood: "#핫플레이스 #만남의장소", exit: "11번 출구" },
        { name: "교대", mood: "#법원 #곱창맛집", exit: "14번 출구" },
        { name: "서초", mood: "#예술의전당", exit: "3번 출구" },
        { name: "방배", mood: "#서리풀공원", exit: "1번 출구" },
        { name: "사당", mood: "#교통의요지 #등산", exit: "4번 출구" },
        { name: "낙성대", mood: "#쟝블랑제리 #공원", exit: "4번 출구" },
        { name: "서울대입구", mood: "#샤로수길", exit: "2번 출구" },
        { name: "봉천", mood: "#시장맛집", exit: "1번 출구" },
        { name: "신림", mood: "#백순대 #도림천", exit: "3번 출구" },
        { name: "신대방", mood: "#보라매공원", exit: "2번 출구" },
        { name: "구로디지털단지", mood: "#깔깔거리", exit: "2번 출구" },
        { name: "대림", mood: "#차이나타운", exit: "12번 출구" },
        { name: "신도림", mood: "#디큐브시티", exit: "1번 출구" },
        { name: "문래", mood: "#창작촌", exit: "7번 출구" },
        { name: "영등포구청", mood: "#골목맛집", exit: "4번 출구" },
        { name: "당산", mood: "#한강연결", exit: "4번 출구" },
        { name: "합정", mood: "#메세나폴리스 #카페", exit: "7번 출구" },
        { name: "홍대입구", mood: "#연남동 #버스킹", exit: "9번 출구" },
        { name: "신촌", mood: "#대학가 #빨간거울", exit: "2번 출구" },
        { name: "이대", mood: "#쇼핑거리", exit: "2번 출구" },
        { name: "아현", mood: "#간장게장맛집", exit: "4번 출구" },
        { name: "충정로", mood: "#오래된아파트", exit: "9번 출구" }
    ],
    "3호선": [
        { name: "대화", mood: "#킨텍스", exit: "1번 출구" },
        { name: "주엽", mood: "#호수공원", exit: "2번 출구" },
        { name: "정발산", mood: "#라페스타 #웨돔", exit: "1번 출구" },
        { name: "마두", mood: "#법조타운", exit: "1번 출구" },
        { name: "백석", mood: "#벨라시타", exit: "1번 출구" },
        { name: "대곡", mood: "#논밭뷰", exit: "1번 출구" },
        { name: "화정", mood: "#덕양구중심", exit: "1번 출구" },
        { name: "원당", mood: "#꽃시장", exit: "1번 출구" },
        { name: "삼송", mood: "#스타필드고양", exit: "3번 출구" },
        { name: "구파발", mood: "#진관사 #은평한옥마을", exit: "1번 출구" },
        { name: "연신내", mood: "#먹자골목", exit: "6번 출구" },
        { name: "불광", mood: "#NC백화점", exit: "6번 출구" },
        { name: "경복궁", mood: "#서촌 #통인시장", exit: "2번 출구" },
        { name: "안국", mood: "#북촌 #인사동", exit: "2번 출구" },
        { name: "종로3가", mood: "#익선동 #노포", exit: "6번 출구" },
        { name: "을지로3가", mood: "#힙지로 #만선호프", exit: "10번 출구" },
        { name: "동대입구", mood: "#장충동 #족발", exit: "3번 출구" },
        { name: "약수", mood: "#금돼지식당", exit: "1번 출구" },
        { name: "압구정", mood: "#가로수길 #갤러리", exit: "6번 출구" },
        { name: "신사", mood: "#쇼핑 #맛집", exit: "8번 출구" },
        { name: "잠원", mood: "#한강지구", exit: "4번 출구" },
        { name: "고속터미널", mood: "#파미에스테이션 #꽃시장", exit: "1번 출구" },
        { name: "교대", mood: "#법조타운", exit: "14번 출구" },
        { name: "남부터미널", mood: "#예술의전당", exit: "5번 출구" },
        { name: "양재", mood: "#말죽거리", exit: "1번 출구" },
        { name: "도곡", mood: "#타워팰리스", exit: "1번 출구" },
        { name: "대치", mood: "#학원가", exit: "1번 출구" },
        { name: "학여울", mood: "#SETEC", exit: "1번 출구" },
        { name: "대청", mood: "#마루공원", exit: "1번 출구" },
        { name: "일원", mood: "#삼성서울병원", exit: "1번 출구" },
        { name: "수서", mood: "#SRT", exit: "1번 출구" },
        { name: "가락시장", mood: "#회센터", exit: "2번 출구" },
        { name: "오금", mood: "#성내천", exit: "1번 출구" }
    ],
    "4호선": [
        { name: "진접", mood: "#신도시 #조용한", exit: "1번 출구" },
        { name: "오남", mood: "#아파트단지", exit: "1번 출구" },
        { name: "별내별가람", mood: "#별내신도시", exit: "1번 출구" },
        { name: "당고개", mood: "#달동네감성 #수락산", exit: "1번 출구" },
        { name: "상계", mood: "#당현천", exit: "1번 출구" },
        { name: "노원", mood: "#강북핫플 #만남의광장", exit: "2번 출구" },
        { name: "창동", mood: "#포장마차", exit: "1번 출구" },
        { name: "쌍문", mood: "#응답하라1988 #쌍리단길", exit: "2번 출구" },
        { name: "수유", mood: "#먹자골목", exit: "7번 출구" },
        { name: "미아사거리", mood: "#백화점 #먹자골목", exit: "2번 출구" },
        { name: "성신여대입구", mood: "#대학가 #예쁜카페", exit: "1번 출구" },
        { name: "한성대입구", mood: "#성북동 #나폴레옹과자점", exit: "6번 출구" },
        { name: "혜화", mood: "#대학로 #연극", exit: "2번 출구" },
        { name: "동대문", mood: "#DDP #패션시장", exit: "1번 출구" },
        { name: "충무로", mood: "#남산골한옥마을 #영화", exit: "4번 출구" },
        { name: "명동", mood: "#남산타워 #길거리음식", exit: "3번 출구" },
        { name: "회현", mood: "#남대문시장", exit: "5번 출구" },
        { name: "서울역", mood: "#기차여행", exit: "1번 출구" },
        { name: "숙대입구", mood: "#청파동 #맛집", exit: "8번 출구" },
        { name: "삼각지", mood: "#용리단길 #전쟁기념관", exit: "3번 출구" },
        { name: "신용산", mood: "#아모레퍼시픽", exit: "1번 출구" },
        { name: "이촌", mood: "#국립중앙박물관 #가족공원", exit: "2번 출구" },
        { name: "동작", mood: "#현충원 #노을카페", exit: "1번 출구" },
        { name: "총신대입구(이수)", mood: "#먹자골목", exit: "13번 출구" },
        { name: "사당", mood: "#등산객 #교통요지", exit: "4번 출구" },
        { name: "남태령", mood: "#서울과 과천을 이어주는 곳", exit: "1번 출구" },
        { name: "선바위", mood: "#미술관 #카페", exit: "2번 출구" },
        { name: "경마공원", mood: "#경마 #가족나들이", exit: "1번 출구" },
        { name: "대공원", mood: "#서울대공원 #동물원", exit: "2번 출구" },
        { name: "과천", mood: "#정부청사", exit: "1번 출구" },
        { name: "인덕원", mood: "#먹거리촌", exit: "4번 출구" },
        { name: "범계", mood: "#안양핫플", exit: "2번 출구" },
        { name: "금정", mood: "#환승역", exit: "1번 출구" },
        { name: "산본", mood: "#중심상가", exit: "3번 출구" },
        { name: "대야미", mood: "#갈치저수지", exit: "1번 출구" },
        { name: "중앙", mood: "#안산중앙동", exit: "1번 출구" },
        { name: "초지", mood: "#와스타디움", exit: "1번 출구" },
        { name: "안산", mood: "#다문화거리", exit: "1번 출구" },
        { name: "오이도", mood: "#빨간등대 #조개구이", exit: "2번 출구 버스이동" }
    ],
    "5호선": [
        { name: "방화", mood: "#조용한동네", exit: "1번 출구" },
        { name: "김포공항", mood: "#여행의설렘 #롯데몰", exit: "3번 출구" },
        { name: "마곡", mood: "#서울식물원 #신도시", exit: "1번 출구" },
        { name: "발산", mood: "#맛집천국 #NC백화점", exit: "1번 출구" },
        { name: "화곡", mood: "#강서구청근처 #육탕상점대존맛", exit: "1번 출구" },
        { name: "목동", mood: "#학원가 #행복한세상", exit: "1번 출구" },
        { name: "오목교", mood: "#현대백화점 #안양천", exit: "2번 출구" },
        { name: "영등포구청", mood: "#골목맛집", exit: "4번 출구" },
        { name: "여의도", mood: "#IFC몰 #금융권", exit: "3번 출구" },
        { name: "여의나루", mood: "#한강피크닉 #더현대", exit: "2번 출구" },
        { name: "마포", mood: "#돼지갈비거리", exit: "1번 출구" },
        { name: "공덕", mood: "#전골목 #족발거리", exit: "5번 출구" },
        { name: "광화문", mood: "#교보문고 #세종문화회관 #청계천", exit: "2번 출구" },
        { name: "종로3가", mood: "#익선동 #포차", exit: "4번 출구" },
        { name: "을지로4가", mood: "#방산시장 #조명", exit: "1번 출구" },
        { name: "왕십리", mood: "#엔터식스", exit: "4번 출구" },
        { name: "군자", mood: "#곱창거리", exit: "6번 출구" },
        { name: "천호", mood: "#쭈꾸미골목 #현대백화점", exit: "6번 출구" },
        { name: "방이", mood: "#올림픽공원", exit: "4번 출구" },
        { name: "올림픽공원", mood: "#콘서트 #나홀로나무", exit: "3번 출구" },
        { name: "미사", mood: "#미사경정공원 #카페 #만남의광장", exit: "1번 출구" },
        { name: "하남검단산", mood: "#등산 #팔당뷰 #스타필드", exit: "3번 출구" }
    ],
    "6호선": [
        { name: "응암", mood: "#불광천산책", exit: "4번 출구" },
        { name: "역촌", mood: "#은평평화공원", exit: "1번 출구" },
        { name: "불광", mood: "#NC백화점", exit: "6번 출구" },
        { name: "디지털미디어시티", mood: "#방송국구경", exit: "9번 출구" },
        { name: "월드컵경기장", mood: "#하늘공원 #홈플러스", exit: "1번 출구" },
        { name: "마포구청", mood: "#망원한강공원연결", exit: "1번 출구" },
        { name: "망원", mood: "#망리단길 #망원시장", exit: "2번 출구" },
        { name: "합정", mood: "#메세나폴리스", exit: "7번 출구" },
        { name: "상수", mood: "#상수카페거리", exit: "4번 출구" },
        { name: "광흥창", mood: "#신수동맛집", exit: "4번 출구" },
        { name: "대흥", mood: "#경의선숲길", exit: "3번 출구" },
        { name: "공덕", mood: "#갈매기살골목", exit: "10번 출구" },
        { name: "효창공원앞", mood: "#용문시장 #공원", exit: "1번 출구" },
        { name: "삼각지", mood: "#용리단길 #차돌박이", exit: "3번 출구" },
        { name: "녹사평", mood: "#경리단길 #해방촌", exit: "1번 출구" },
        { name: "이태원", mood: "#클럽 #외국음식", exit: "1번 출구" },
        { name: "한강진", mood: "#패션파이브 #뮤지컬", exit: "1번 출구" },
        { name: "버티고개", mood: "#남산산책", exit: "1번 출구" },
        { name: "약수", mood: "#금돼지식당", exit: "1번 출구" },
        { name: "신당", mood: "#중앙시장 #쌀떡볶이", exit: "7번 출구" },
        { name: "동묘앞", mood: "#구제시장", exit: "3번 출구" },
        { name: "고려대", mood: "#개운사", exit: "1번 출구" },
        { name: "월곡", mood: "#동덕여대", exit: "1번 출구" },
        { name: "석계", mood: "#매운족발", exit: "1번 출구" },
        { name: "태릉입구", mood: "#장미공원", exit: "8번 출구" }
    ],
    "7호선": [
        { name: "장암", mood: "#의정부끝", exit: "1번 출구" },
        { name: "노원", mood: "#문화의거리", exit: "4번 출구" },
        { name: "중계", mood: "#등나무근린공원", exit: "1번 출구" },
        { name: "태릉입구", mood: "#서울생활사박물관", exit: "4번 출구" },
        { name: "상봉", mood: "#코스트코", exit: "1번 출구" },
        { name: "어린이대공원", mood: "#동물원 #건대후문", exit: "1번 출구" },
        { name: "뚝섬유원지", mood: "#한강자양지구 #치맥", exit: "2번 출구" },
        { name: "청담", mood: "#명품거리", exit: "8번 출구" },
        { name: "강남구청", mood: "#웨딩샵 #세관", exit: "1번 출구" },
        { name: "논현", mood: "#영동시장", exit: "2번 출구" },
        { name: "반포", mood: "#아파트단지", exit: "1번 출구" },
        { name: "고속터미널", mood: "#고터지하상가", exit: "8-1번 출구" },
        { name: "이수", mood: "#남성사계시장", exit: "10번 출구" },
        { name: "남구로", mood: "#인력시장", exit: "1번 출구" },
        { name: "가산디지털단지", mood: "#아울렛쇼핑", exit: "4번 출구" },
        { name: "광명사거리", mood: "#광명전통시장", exit: "1번 출구" },
        { name: "까치울", mood: "#작동카페거리", exit: "3번 출구" },
        { name: "상동", mood: "#호수공원", exit: "1번 출구" }
    ],
    "8호선": [
        { name: "다산", mood: "#다산신도시 #현대프리미엄아울렛", exit: "1번 출구" },
        { name: "구리", mood: "#돌다리시장", exit: "1번 출구" },
        { name: "암사", mood: "#선사유적지", exit: "1번 출구" },
        { name: "천호", mood: "#강동역연결", exit: "5번 출구" },
        { name: "몽촌토성", mood: "#올림픽공원", exit: "1번 출구" },
        { name: "잠실", mood: "#롯데월드", exit: "10번 출구" },
        { name: "석촌", mood: "#송리단길", exit: "2번 출구" },
        { name: "송파", mood: "#헬리오시티", exit: "1번 출구" },
        { name: "가락시장", mood: "#수산대전", exit: "1번 출구" },
        { name: "문정", mood: "#법조타운", exit: "3번 출구" },
        { name: "복정", mood: "#동서울대", exit: "1번 출구" },
        { name: "남한산성입구", mood: "#등산", exit: "1번 출구" },
        { name: "모란", mood: "#모란시장", exit: "5번 출구" }
    ],
    "9호선": [
        { name: "김포공항", mood: "#국내선여행", exit: "1번 출구" },
        { name: "마곡나루", mood: "#서울식물원", exit: "1번 출구" },
        { name: "가양", mood: "#홈플러스본사", exit: "1번 출구" },
        { name: "등촌", mood: "#강서구청사거리", exit: "1번 출구" },
        { name: "선유도", mood: "#선유도공원", exit: "2번 출구" },
        { name: "당산", mood: "#한강산책로", exit: "4번 출구" },
        { name: "국회의사당", mood: "#윤중로벚꽃", exit: "1번 출구" },
        { name: "여의도", mood: "#IFC몰", exit: "3번 출구" },
        { name: "샛강", mood: "#생태공원", exit: "1번 출구" },
        { name: "노량진", mood: "#컵밥", exit: "3번 출구" },
        { name: "흑석", mood: "#중앙대학교", exit: "3번 출구" },
        { name: "동작", mood: "#현충원", exit: "1번 출구" },
        { name: "구반포", mood: "#애플하우스", exit: "1번 출구" },
        { name: "신반포", mood: "#반포한강공원", exit: "1번 출구" },
        { name: "고속터미널", mood: "#파미에스테이션", exit: "1번 출구" },
        { name: "사평", mood: "#조용한도서관", exit: "1번 출구" },
        { name: "신논현", mood: "#강남교보타워", exit: "6번 출구" },
        { name: "언주", mood: "#차병원", exit: "1번 출구" },
        { name: "선정릉", mood: "#세계문화유산", exit: "3번 출구" },
        { name: "삼성중앙", mood: "#코엑스후문", exit: "1번 출구" },
        { name: "봉은사", mood: "#아쿠아리움", exit: "7번 출구" },
        { name: "종합운동장", mood: "#두산베어스V7", exit: "9번 출구" },
        { name: "석촌고분", mood: "#백제유적", exit: "1번 출구" },
        { name: "송파나루", mood: "#송리단길", exit: "1번 출구" },
        { name: "중앙보훈병원", mood: "#일자산공원", exit: "1번 출구" }
    ],
    "수인분당선": [
        { name: "청량리", mood: "#전통시장", exit: "1번 출구" },
        { name: "서울숲", mood: "#피크닉", exit: "4번 출구" },
        { name: "압구정로데오", mood: "#도산공원", exit: "5번 출구" },
        { name: "강남구청", mood: "#오피스타운", exit: "1번 출구" },
        { name: "선릉", mood: "#정릉", exit: "10번 출구" },
        { name: "도곡", mood: "#양재천", exit: "4번 출구" },
        { name: "한티", mood: "#학원가", exit: "3번 출구" },
        { name: "수서", mood: "#SRT", exit: "1번 출구" },
        { name: "복정", mood: "#위례입구", exit: "2번 출구" },
        { name: "가천대", mood: "#대학가", exit: "1번 출구" },
        { name: "야탑", mood: "#종합버스터미널", exit: "1번 출구" },
        { name: "서현", mood: "#AK플라자", exit: "1번 출구" },
        { name: "수내", mood: "#중앙공원", exit: "1번 출구" },
        { name: "정자", mood: "#카페거리", exit: "3번 출구" },
        { name: "죽전", mood: "#신세계백화점", exit: "1번 출구" },
        { name: "기흥", mood: "#AK몰", exit: "1번 출구" },
        { name: "수원", mood: "#로데오거리 #행궁동 #AK플라자", exit: "7번 출구" },
        { name: "인천", mood: "#차이나타운", exit: "1번 출구" }
    ],
    "신분당선": [
        { name: "신사", mood: "#가로수길", exit: "8번 출구" },
        { name: "논현", mood: "#먹자골목", exit: "3번 출구" },
        { name: "신논현", mood: "#강남역북측", exit: "7번 출구" },
        { name: "강남", mood: "#핫플레이스", exit: "4번 출구" },
        { name: "양재", mood: "#말죽거리", exit: "1번 출구" },
        { name: "양재시민의숲", mood: "#꽃시장", exit: "1번 출구" },
        { name: "판교", mood: "#IT밸리 #테크노밸리 #현대백화점", exit: "3번 출구" },
        { name: "정자", mood: "#정자엠코헤리츠", exit: "3번 출구" },
        { name: "수지구청", mood: "#수지맛집", exit: "1번 출구" },
        { name: "광교중앙", mood: "#아브뉴프랑", exit: "1번 출구" },
        { name: "광교", mood: "#경기대", exit: "1번 출구" }
    ],
    "경의중앙선": [
        { name: "문산", mood: "#임진각", exit: "1번 출구" },
        { name: "금촌", mood: "#파주시청", exit: "1번 출구" },
        { name: "운정", mood: "#운정호수공원", exit: "1번 출구" },
        { name: "일산", mood: "#일산시장", exit: "1번 출구" },
        { name: "수색", mood: "#철길마을", exit: "1번 출구" },
        { name: "가좌", mood: "#연남동끝자락", exit: "1번 출구" },
        { name: "홍대입구", mood: "#경의선숲길", exit: "6번 출구" },
        { name: "서강대", mood: "#책거리", exit: "2번 출구" },
        { name: "공덕", mood: "#환승성지", exit: "10번 출구" },
        { name: "효창공원앞", mood: "#용문시장", exit: "1번 출구" },
        { name: "용산", mood: "#아이파크몰", exit: "1번 출구" },
        { name: "이촌", mood: "#가족공원", exit: "1번 출구" },
        { name: "옥수", mood: "#한강뷰달리기", exit: "4번 출구" },
        { name: "응봉", mood: "#개나리동산", exit: "1번 출구" },
        { name: "왕십리", mood: "#곱창거리", exit: "6번 출구" },
        { name: "회기", mood: "#경희대파전", exit: "1번 출구" },
        { name: "구리", mood: "#롯데백화점", exit: "3번 출구" },
        { name: "운길산", mood: "#물의정원", exit: "1번 출구" },
        { name: "양평", mood: "#해장국 #들꽃수목원", exit: "1번 출구" },
        { name: "용문", mood: "#용문사은행나무", exit: "1번 출구" }
    ]
};

// [색상 정의] 노선별 색상 추가
const lineColors = {
    "1호선": "#0052A4",
    "2호선": "#00A84D",
    "3호선": "#EF7C1C",
    "4호선": "#00A5DE",
    "5호선": "#996CAC",
    "6호선": "#CD7C2F",
    "7호선": "#747F00",
    "8호선": "#E6186C",
    "9호선": "#BDB092",
    "수인분당선": "#FABE00",
    "신분당선": "#D4003B",
    "경의중앙선": "#77C4A3",
    "default": "#00ff88"
};

const lineColor = lineColors[selectedLine] || lineColors.default;

// 테두리 색상과 함께 '네온사인' 효과 추가
container.style.borderColor = lineColor;
container.style.boxShadow = `0 0 20px ${lineColor}44`; // 끝에 44는 투명도야!